name: Linters

on: [push, pull_request]

jobs:
  rustfmt:
    name: Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable
          rustup component add rustfmt

      - name: Check Formatting
        run: cargo fmt --all -- --check
